### ISSUE TITLE
Alphabetical Order doesn't work for me

### ISSUE THREAD

**Issue by brascoder** [Marqu1s/MyGrams#1]
When I run the script and enter a list of words, it hangs. When I run it and enter no words, it shows a success message with no list

**Comment by Marqu1s** [comment]
When you say hang...what do you mean?

**Comment by brascoder** [comment]
it just sits there and doesn't do anything. After further investigation tho, I see that it's waiting for my input. You may want to tell the user that they need to enter 1 word at a time and hit enter after each word, then hit enter with no word to sort. I enter a list of words all at once.
